Lang = {
    title = 'Hostage',
    errors = {
        invalid = 'Invalid request.',
        timeout = 'No response from server, try again.',
        slow_down = 'Slow down.',
        cooldown = 'You need to wait before doing that again.',
        no_weapon = 'You need a firearm in your hands.',
        blocked_weapon = 'You can\'t take a hostage with that weapon.',
        not_loaded = 'Your weapon isn\'t loaded.',
        cant_hold_weapon = 'You need a pistol or SMG to hold someone.',
        invalid_target = 'You can\'t take this person hostage.',
        no_los = 'You don\'t have a clear line to them.',
        too_far = 'You\'re too far away.',
        no_control = 'Couldn\'t get control of that person, try again.',
        already_hostage = 'Someone already has this person.',
        ped_cooldown = 'This person is too shaken to be taken again yet.',
        max_hostages = 'You can\'t control any more hostages.',
        max_held = 'You\'re already holding someone.',
        not_enough_police = 'Not enough police around.',
        police_blocked = 'You can\'t do that on duty.',
        you_are_down = 'You can\'t do that right now.',
        not_your_hostage = 'That\'s not your hostage.',
        hostage_gone = 'Your hostage is gone.',
        hostage_dead = 'Your hostage is dead.',
        bad_state = 'You can\'t do that right now.',
        no_vehicle = 'No vehicle nearby.',
        no_seat = 'No free passenger seat.',
        vehicle_locked = 'That vehicle is locked.',
        no_point = 'Aim at a spot to send them to.',
        disabled = 'That is disabled.',
        not_police = 'Only police can do that.',
        captor_close = 'The captor is too close.',
        no_negotiation = 'No active negotiation.',
        neg_exists = 'You already have an active negotiation.',
        need_hostages = 'You need hostages to negotiate.',
        no_demands = 'Pick at least one demand.',
    },
    reactions = {
        surrender = 'They raise their hands and comply.',
        panic = 'They panic but comply.',
        cry = 'They break down crying and comply.',
        scream = 'They scream for help!',
        refuse = 'They refuse to cooperate. Threaten them.',
        run = 'They bolt!',
    },
    states = {
        THREATENED = 'Threatened', COMPLIANT = 'Compliant', HELD = 'Held', KNEELING = 'Kneeling',
        VEHICLE = 'In Vehicle', RELEASED = 'Released', ESCAPED = 'Escaped', DEAD = 'Dead',
    },
    modes = { stay = 'Staying', follow = 'Following', handsup = 'Hands Up', cower = 'Cowering', cry = 'Crying', moveto = 'Moving', refuse = 'Refusing' },
    actions = {
        grab = 'Grab Hostage', letgo = 'Let Go (Keep Control)', follow = 'Follow Me', stay = 'Stay Here',
        handsup = 'Hands Up', kneel = 'Kneel', stand = 'Stand Up', moveto = 'Move To Spot',
        threaten = 'Threaten', vehicle_in = 'Put In Vehicle', vehicle_out = 'Order Out Of Vehicle',
        vehicle_remove = 'Pull Out & Follow', push = 'Push Away', release = 'Release Hostage', execute = 'Execute',
    },
    menu = {
        title = 'Hostages',
        none = 'You have no hostages',
        negStart = 'Start Negotiation',
        negView = 'View Negotiation',
        distance = '%.1fm away',
        notNearby = 'Not nearby',
    },
    target = {
        take = 'Take Hostage',
        grab = 'Grab Hostage',
        commands = 'Hostage Commands',
        rescue = 'Secure Civilian',
    },
    holdHelp = '[RMB] Aim  \n[R] Reload  \n[E] Let Go  \n[X] Push Away  \n[H] Execute',
    escaped = 'Your hostage escaped!',
    released = 'Hostage released.',
    died = 'Your hostage died.',
    rescued = 'Police secured your hostage!',
    youRescued = 'Civilian secured.',
    executeConfirm = 'Execute this hostage? This cannot be undone.',
    neg = {
        title = 'Negotiation',
        label = 'Location / Situation',
        custom = 'Custom demand',
        created = 'Negotiation opened. Police have been notified.',
        newForPolice = 'New hostage negotiation: %s',
        updated = 'Police responded to your demands.',
        closed = 'Negotiation closed.',
        status = 'Status',
        counter = 'Counter offer',
        statuses = {
            pending = 'Pending', Accepted = 'Accepted', Denied = 'Denied', Countered = 'Countered',
            CounterAccepted = 'Counter Accepted', CounterRejected = 'Counter Rejected',
        },
        acceptCounter = 'Accept Counter',
        rejectCounter = 'Reject Counter',
        close = 'Close Negotiation',
        none = 'No open negotiations',
        criminalReplied = 'Suspect answered a counter offer (%s)',
    },
}
